feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 910.777
cam_fy: 910.656
cam_cx: 639.846
cam_cy: 355.401

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/imu_data"

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    90
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /camera/color/image_raw
    #xiyuan
    Rcl: [-0.134582, -0.990831, -0.0119257,
         -0.0427573, 0.0178307, -0.998926,
          0.98998, -0.133927, -0.0447649]
    Pcl: [0.0320964, -0.0579195, -0.0543362]
    
